package sh.app2.zsalesorder_v2_srv.v1.helpers;
/*
 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1
*/
import java.util.List;

import com.sap.gwpa.proxy.RequestStatus;
import com.sap.mobile.lib.request.IResponse;

/**
 * Interface for Request Handler listener.
 * Contains methods that handle completed requests and cases
 * when authentication is needed.
 */
public interface IZSALESORDER_V2_SRVRequestHandlerListener
{
    /**
     * This method can do whatever comes in mind.
     * It receives the request ID, according to it the developer 
     * knows which entries were parsed and sent to this method.
     * Also it receives the request's status, according to it he can know whether
     * the request has succeeded or failed.
     * We recommend to first check that the status is OK.
     * 
     * @param requestID - The ID of the request.
     * @param entries - the parsed collection entries.
     * @param requestStatus - the status of the request.
     */
    public void requestCompleted(ZSALESORDER_V2_SRVRequestID requestID, List<?> entries, RequestStatus requestStatus);
    
	/**
     * This method can do whatever comes in mind.
     * It receives the batch ID, according to it the developer 
     * knows which batch request was completed.
     * Also it receives the request's status, according to it he can know whether
     * the request has succeeded or failed.
     * We recommend to first check that the status is OK.
     * 
     * @param batchID batch id
     * @param response the batch response
     * @param requestStatus the status of the request.
     */
    public void batchCompleted(String batchID, IResponse response, RequestStatus requestStatus);
    
    /**
     * Handles the case when authentication is needed, e.g. show
     * the login page.
     * 
     * @param message - the error message.
     */
    public void authenticationNeeded(String message);
}