package sh.app2.zsalesorder_v2_srv.v1.entitytypes;
/*

 Auto-Generated by SAP NetWeaver Gateway Productivity Accelerator, Version 1.1.1

*/
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.sap.gwpa.proxy.BaseEntityType;
import com.sap.gwpa.proxy.ODataQuery;
import com.sap.gwpa.proxy.TypeConverter;
import com.sap.mobile.lib.parser.IODataEntry;
import com.sap.mobile.lib.parser.IODataProperty;
import com.sap.mobile.lib.parser.IODataSchema;
import com.sap.mobile.lib.parser.IODataServiceDocument;
import com.sap.mobile.lib.parser.IParser;
import com.sap.mobile.lib.parser.ODataEntry;

/**
 * OrderScheduleIn Entity Type 
 *
 * <br>key (ItmNumber)
 */
public class OrderScheduleIn extends BaseEntityType 
{
	// OrderScheduleIn properties
    private BigDecimal ReqQty;
    private String ItmNumber;

	// reference to the parser
	private IParser parser;
	// reference to the schema
	private IODataSchema schema;

	private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");


	private static Map<String, String> orderscheduleinLabels;

	private static Map<String, String> orderscheduleinTypes;	
	
	/**
	 * Constructor
	 * @param entry
	 * @throws MalformedURLException
	 */
	public OrderScheduleIn(final IODataEntry entry, IParser parser, IODataSchema schema) throws MalformedURLException
	{
		super(entry);
		this.ReqQty =  TypeConverter.getAsFloat(entry.getPropertyValue("ReqQty"));
		this.ItmNumber =  TypeConverter.getAsString(entry.getPropertyValue("ItmNumber"));
	    this.parser = parser;
        this.schema = schema;
 	}
	
	/**
	 * OrderScheduleIn Constructor</br>
	 * Dummy values may apply
	 *
	 */
	public OrderScheduleIn( String ItmNumber) 
	{
		super(new ODataEntry());
		
        this.setItmNumber(ItmNumber);
	}



	// OrderScheduleIn properties getters and setters
		
	/**
	 * @return - BigDecimal Order quantity
	 */
	public BigDecimal getReqQty()
	{
		return this.ReqQty;
	}
	
	/**
	 * @param ReqQty - Order quantity
	 */
	public void setReqQty(BigDecimal ReqQty)
	{
		this.ReqQty = ReqQty;
		
		getEntry().putPropertyValue("ReqQty",  String.valueOf(this.ReqQty.floatValue()));
	}
		
	/**
	 * @return - String Sales Document Item
	 */
	public String getItmNumber()
	{
		return this.ItmNumber;
	}
	
	/**
	 * @param ItmNumber - Sales Document Item
	 */
	public void setItmNumber(String ItmNumber)
	{
		this.ItmNumber = ItmNumber;
		
		getEntry().putPropertyValue("ItmNumber", ItmNumber);
	}
	
	/**
	 * @return - representation of the Entity Type object in OData4SAP format
	 */
	public String getStringPayload()  
	{
		String xml = null;
		
		xml = getEntry().toXMLString();
			
		return xml;
	}
	
	/**
	 * @return - self ODataQuery object
	 * @throws MalformedURLException 
	 */
	public ODataQuery getEntityQuery() throws MalformedURLException  
	{
		return new ODataQuery(getEntry().getSelfLink().getUrl());
	}
	
	/**
	 * @return - the date format.
	 */
	public DateFormat getDateFormat()
	{
		return this.dateFormat;
	}


	/**
    * Static method that loads all of the entity type property labels. 
    * This method is called when the service class is initialized.
    * @param service Service document object containing all of the entity type properties.
   	*/	
    public static void loadLabels(IODataServiceDocument service)
    {
    	List<IODataProperty> properties = getSchemaPropertiesFromCollection(service, "OrderScheduleInSet" );
        
    	orderscheduleinLabels = new HashMap<String, String>();
    	orderscheduleinTypes = new HashMap<String, String>();
    	
    	if (properties != null)
    	{
	        for (IODataProperty property : properties) 
	        {
	        	orderscheduleinLabels.put(property.getName(), property.getLabel());
	        	orderscheduleinTypes.put(property.getName(), property.getType());
			}
    	}
    }
    
    
    /**
    * Static method that returns the type for a given property name.
    * @param propertyName Property name.
    * @return Property label.
   	*/
    public static String getTypeForProperty(String propertyName)
    {
        return getLabelFromDictionary(orderscheduleinTypes, propertyName);
    }
    
    
    /**
    * Static method that returns the label for a given property name.
    * @param propertyName Property name.
    * @return Property label.
   	*/
    public static String getLabelForProperty(String propertyName)
    {
        return getLabelFromDictionary(orderscheduleinLabels, propertyName);
    }
}